export const countries = [
  { code: "in", name: "India", flag: "https://flagcdn.com/w40/in.png" },
  { code: "us", name: "United States", flag: "https://flagcdn.com/w40/us.png" },
  {
    code: "gb",
    name: "United Kingdom",
    flag: "https://flagcdn.com/w40/gb.png",
  },
  { code: "ca", name: "Canada", flag: "https://flagcdn.com/w40/ca.png" },
  { code: "au", name: "Australia", flag: "https://flagcdn.com/w40/au.png" },
  { code: "de", name: "Germany", flag: "https://flagcdn.com/w40/de.png" },
  { code: "fr", name: "France", flag: "https://flagcdn.com/w40/fr.png" },
  { code: "jp", name: "Japan", flag: "https://flagcdn.com/w40/jp.png" },
  { code: "cn", name: "China", flag: "https://flagcdn.com/w40/cn.png" },
  { code: "br", name: "Brazil", flag: "https://flagcdn.com/w40/br.png" },
  { code: "za", name: "South Africa", flag: "https://flagcdn.com/w40/za.png" },
  { code: "mx", name: "Mexico", flag: "https://flagcdn.com/w40/mx.png" },
  { code: "ru", name: "Russia", flag: "https://flagcdn.com/w40/ru.png" },
  { code: "it", name: "Italy", flag: "https://flagcdn.com/w40/it.png" },
  { code: "es", name: "Spain", flag: "https://flagcdn.com/w40/es.png" },
  {
    code: "ae",
    name: "United Arab Emirates",
    flag: "https://flagcdn.com/w40/ae.png",
  },
  { code: "sg", name: "Singapore", flag: "https://flagcdn.com/w40/sg.png" },
  { code: "kr", name: "South Korea", flag: "https://flagcdn.com/w40/kr.png" },
  { code: "sa", name: "Saudi Arabia", flag: "https://flagcdn.com/w40/sa.png" },
  { code: "ng", name: "Nigeria", flag: "https://flagcdn.com/w40/ng.png" },
];
